version: '3'

services:

  app:
    image: sabrinasmith/planetarium:file
    # build:
    #   context: .
    #   dockerfile: dockerfile
    container_name: planetarium
    ports:
      - 8080:8080
    environment:
      - VARIABLE=VALUE
    volumes:
      - ./logs/:/logs/

  loki:
    image: grafana/loki:latest
    container_name: logging-loki
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: logging-promtail
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml 
      - ./logs/staticLogs.log:/var/log/staticLogs.log
    command: "--config.file=/etc/promtail/promtail-config.yml"

  grafana:
    image: grafana/grafana:latest # default username/password:admin/admin
    container_name: logging-grafana
    # volumes:
    #   - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki # ensures loki is setup before Grafana tries to interface with it
