server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push 

scrape_configs:
  - job_name: system
    static_configs: # we choose static_configs because our local logs are "static"
      - targets:
          - localhost
        labels:
          job: planetarium
          __path__: /var/log/staticLogs.log